spring:
  profiles:
    active:  dev
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
  datasource:
    url: jdbc:h2:mem:./hoaxify-dev

hoaxify:
  upload-path: uploads-dev
  profile-images: profile
  attachments: attachments

 
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./hoaxify-prod
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false 
hoaxify:
  upload-path: uploads-prod

---
spring:
  profiles: test
hoaxify:
  upload-path: uploads-test
