spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  h2:
    console:
      enabled: true
      path: /h2-console
      
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
  